//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagementItem
    {
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public string sourceResourceId { get; set; }
        public string imagesLocation { get; set; }
        public string imagesResourceGroup { get; set; }
        public string imagePrefix { get; set; }
        public string imageVersion { get; set; }
    }
}
